### ISSUE TITLE
react-datetime@2.6.1 seems to break build

### ISSUE THREAD

**Issue by FlorentD** [kadirahq/storybook-addon-knobs#66] opened 2016-10-27 09:27 UTC
As `react-datetime@2.6.1`  skip `/src` folder into his build, it breaks `npm run storybook`command.
fallback `react-datime` to 2.6.0 fix it.

Simon Egersand (react-datetime) will create a fix asap o//

**Comment by aivarsak** [comment] 2016-10-27 10:55
Is this error "@kadira/storybook-addon-knobs/storybook-addon-knobs.d.ts:26:16 
'date', which lacks return-type annotation, implicitly has an 'any' return type." related to react-datetime@2.6.1?

**Comment by aivarsak** [comment] 2016-10-27 10:56
Adding return type to date function definition eliminates the compile error.

**Comment by smoke** [comment] 2016-10-27 11:30
Checking this comment https://github.com/YouCanBookMe/react-datetime/commit/bd232d91272e386b01b8748c5dbb018e177eaffd version 2.6.2 is now available and the problem is resolved.

As for @aivarsak question - this is part of the original error:
```
ERROR in ./~/react-datetime/DateTime.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/DaysView in /my-project/node_modules/react-datetime
 @ ./~/react-datetime/DateTime.js 5:12-37

ERROR in ./~/react-datetime/DateTime.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/MonthsView in /my-project/node_modules/react-datetime
 @ ./~/react-datetime/DateTime.js 6:14-41

ERROR in ./~/react-datetime/DateTime.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/YearsView in /my-project/node_modules/react-datetime
 @ ./~/react-datetime/DateTime.js 7:13-39

ERROR in ./~/react-datetime/DateTime.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/TimeView in /my-project/node_modules/react-datetime
 @ ./~/react-datetime/DateTime.js 8:12-37

ERROR in ./~/react-datetime/DateTime.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/onClickOutside in /my-project/node_modules/react-datetime
 @ ./~/react-datetime/DateTime.js 15:2-33
```

**Comment by revov** [comment] 2016-10-27 11:41
As the dependency here is marked as `"react-datetime": "^2.6.0"` this will automatically pull 2.6.2 on fresh installs and fix the error.

@FlorentD, I think we can close this issue.

**Comment by roonyh** [comment] 2016-10-27 11:45
@revov Great! Will close this now. Thanks for informing @FlorentD

**Closed by roonyh** 2016-10-27 11:45 UTC
